name: Cygwin
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]
        vs: [2019]
        buildarch: [0,1] # BuildMode || 1 == 64bit | 0 == 32bit
      fail-fast: false
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - uses: actions/cache@v2.1.1
        with:
          path: C:\Users\runneradmin\AppData\Local\Temp\chocolatey
          key: ${{ runner.os }}-chocolatey-${{ matrix.os }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-chocolatey-${{ matrix.os }}-
            ${{ runner.os }}-chocolatey-
      - uses: actions/cache@v2.1.1
        id: cygwin-cache
        with:
          path: C:/tools/cygwin
          key: ${{ runner.os }}-cygwin-${{ matrix.os }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-cygwin-${{ matrix.os }}-
            ${{ runner.os }}-cygwin-
      - name: Install cygwin base packages with chocolatey
        run: |
          choco config get cacheLocation
          choco install --no-progress nsis
      - name: Install cygwin additional packages
        if: steps.cygwin-cache.outputs.cache-hit != 'true'
        run: |
          curl -sLO https://www.cygwin.com/setup-x86_64.exe
          .\setup-x86_64.exe -qgnNdO -R C:/tools/cygwin -s http://mirrors.kernel.org/sourceware/cygwin/ -P autoconf,bison,curl,flex,gcc-core,git,libcrypt-devel,libedit-devel,libffi-devel,libgdbm-devel,libgmp-devel,libintl-devel,libncurses-devel,libreadline-devel,libssl-devel,libuuid-devel,make,nasm,patch,python,ruby,tcl-tk-devel,zlib-devel,p7zip-full
        shell: cmd
      - name: Checkout
        run: |
          setx /m PATH "C:\tools\cygwin\usr\bin;C:\tools\cygwin\bin;%PATH%"
          touch.exe .gitconfig||true
          git config --global core.autoCRLF false
          git config --global http.postBuffer 540000000
          git clone --single-branch --depth=1 https://github.com/koumaza/vcxsrv.git vcxsrv
          cd vcxsrv/
          curl.exe -sLO https://github.com/koumaza/multithread-submodule-clone/raw/master/mdsubmclone.bash && bash.exe mdsubmclone.bash
        if: github.event_name == 'push'
        shell: cmd
      - name: Checkout a pull request
        run: |
          setx /m PATH "C:\tools\cygwin\usr\bin;C:\tools\cygwin\bin;%PATH%"
          touch.exe .gitconfig||true
          git config --global core.autoCRLF false
          git config --global http.postBuffer 540000000
          git clone --single-branch --depth=1 --branch=${{ github.event.pull_request.head.ref }} https://github.com/${{ github.event.pull_request.head.repo.full_name }} vcxsrv
          cd vcxsrv/
          curl.exe -sLO https://github.com/koumaza/multithread-submodule-clone/raw/master/mdsubmclone.bash && bash.exe mdsubmclone.bash
        if: github.event_name == 'pull_request'
        shell: cmd
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.1
      - name: Build All
        env:
          perlversion: 5.30.3.1
        run: |
          curl -sLO http://strawberryperl.com/download/$perlversion/strawberry-perl-$perlversion-64bit-PDL.zip
          7z x strawberry-perl-$perlversion-64bit-PDL.zip -o/c/perl/
          curl -sLO https://www.python.org/ftp/python/3.9.0/python-3.9.0b5-embed-amd64.zip
          7z x python-*-embed-amd64.zip -o/c/python3
          cd vcxsrv
          export PATH=$PWD/tools:$PWD/tools/mhmake:$PWD/tools/plink:/c/tools/cygwin/usr/bin:/c/tools/cygwin/bin:$PATH
          bash buildall.sh ${{ matrix.buildarch }} 12
        shell: bash
